version: '2'
services:
  db:
    build: ./db
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'hQ9GmpsE4ra'
  web:
      build: ./web
      ports:
        - '80:80'
      volumes:
        - ./html:/var/www/html
      depends_on:
        - db
