version: '2'
services:
  db:
    build: ./db
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
  web:
      build: ./web
      ports:
        - '80:80'
      volumes:
        - ./html:/var/www/html
      depends_on:
        - db
